{% set name = "pyg4ometry" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyg4ometry-{{ version }}.tar.gz
  sha256: dde0877bc1c214cedaec7b8015d201d215977f2c5c86e307de6f5451219034b0

build:
  # no recent qt builds for ppc
  skip: true  # [ppc64le and py==313]
  entry_points:
    - pyg4ometry = pyg4ometry.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.20
    - make
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython
    - pybind11 >=2.6
    - {{ pin_compatible('numpy') }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - scikit-build-core ==0.5
    - antlr4-tools ==0.2.1
    - python-build
    - cgal
    - occt
    - mpfr
    - gmp
    - libgl-devel  # [linux]
  run:
    - python
    - importlib-resources
    - antlr4-python3-runtime ==4.13.1
    - matplotlib-base
    - networkx >=3
    - pandas
    - scipy
    - sympy >=1.7
    - vtk
    - cgal
    - occt
    - mpfr
    - gmp
    - configparser
    - testtools

test:
  imports:
    - pyg4ometry
  commands:
    - pip check
    - pyg4ometry --help
  requires:
    - pip
    - setuptools

about:
  home: https://github.com/g4edge/pyg4ometry
  license: GPL-3.0-only
  license_file:
    - LICENSE
  summary: Python code for rapid creation and conversion of radiation transport Monte Carlo (Geant4 and Fluka) geometries
  doc_url: https://pyg4ometry.readthedocs.io
  dev_url: https://github.com/g4edge/pyg4ometry

extra:
  recipe-maintainers:
    - chrisburr
    - stewartboogert
    - gipert
