{% set name = "pyg4ometry" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyg4ometry-{{ version }}.tar.gz
  sha256: 35f7988ae5a08eff7a6e02de6fc2b742553d8002e91d6f3b090d421c807557ee

build:
  skip: true  # [win or py<38]
  entry_points:
    - pyg4ometry = pyg4ometry.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8.0
    - cython
    - cmake >=3.20
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cgal
    - occt
    - pybind11 >=2.6
    - setuptools >=42
    - setuptools-scm >=3.4
    - scikit-build-core ==0.5
    - antlr4-tools ==0.2.1
    - python-build
    - pip
    - matplotlib-base
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]

  run:
    - python >=3.8.0
    - importlib-resources
    - antlr4-python3-runtime ==4.13.1
    - configparser
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - scipy
    - sympy 
    - testtools
    - occt
    - vtk
    - gmp
    - mpfr
    - {{ stdlib('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    
test:
  imports:
    - pyg4ometry
  commands:
    - pip check
    - pyg4ometry --help
  requires:
    - pip

about:
  home: https://github.com/g4edge/pyg4ometry
  license: GPL-3.0-only
  license_file:
    - LICENSE
  summary: Python code for rapid creation and conversion of radiation transport Monte Carlo (Geant4 and Fluka) geometries
  doc_url: https://pyg4ometry.readthedocs.io
  dev_url: https://github.com/g4edge/pyg4ometry

extra:
  recipe-maintainers:
    - chrisburr
