build_platform:
  linux_64: linux_64
  # NOTE: testing on aarch64 and ppc64le fails with:
  #   ImportError: /home/conda/[...]/site-packages/vtkmodules/../../.././././libGLdispatch.so.0: cannot allocate memory in static TLS block
  # linux_aarch64: linux_64
  # linux_ppc64le: linux_64
  osx_64: osx_64
  osx_arm64: osx_64

# issues with TLS allocation order, c.f. https://github.com/conda-forge/conda-forge.github.io/issues/1551
c_stdlib_version:  # [aarch64]
  - 2.34           # [aarch64]

conda_forge_output_validation: true

conda_build:
  pkg_format: '2'

test: native_and_emulated

github:
  branch_name: main
  tooling_branch_name: main
